# Copyright (c) .NET Foundation and Contributors
# See LICENSE file in the project root for full license information.

# This workflow will periodically check .NET nanoFramework dependencies and updates them in the repository it's running.

name: Daily update dependencies

on:
  schedule:
  # At 01:20 UTC every Wed,Fri.
  - cron:  '20 01 * * Wed,Fri'
  repository_dispatch:
    types: update-dependencies

jobs:
  update-dependencies:
    name: nanoFramework
    uses: nanoframework/nf-tools/.github/workflows/update-dependencies.yml@main
    with:
      solutionsToCheck: 'nanoFramework.System.Threading.sln'
    secrets:
      githubAuth: ${{ secrets.NFBOT_GITHUB_ACTIONS }}
